# Generated by Django 3.1.3 on 2020-12-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='events',
            field=models.ManyToManyField(to='events.Event'),
        ),
    ]
